title: Felix Gao's Blog
description: A bored dev documenting his thoughts.
author: Felix Gao

remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-include-cache

markdown: kramdown
highlighter: rouge

minimal_mistakes_skin: dark
